id = "neo-brutalism"
name = "Neo Brutalism"
version = "0.1.0"
schema_version = 1
authors = ["Vishnu Roshan"]
description = "A raw, high-contrast neo-brutalist theme for the Zed editor."
repository = "https://github.com/vishnuroshan/zed-neo-brutalism"